# Generated by Django 5.1.3 on 2024-11-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_task'),
        ('hotel', '0002_delete_foodmenu_alter_bills_guest_and_more'),
        ('room', '0004_foodmenu_alter_roomservices_foodmenu_guest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
