# Generated by Django 5.1.3 on 2024-11-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
        ('room', '0004_foodmenu_alter_roomservices_foodmenu_guest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodMenu',
        ),
        migrations.AlterField(
            model_name='bills',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.guest'),
        ),
        migrations.AlterField(
            model_name='eventattendees',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='room.guest'),
        ),
    ]
